stages:
  extract-code2seq-java-large-test:
    cmd: unzip -q datasets/code2seq-java-large-test.zip -d datasets
    deps:
    - datasets/code2seq-java-large-test.zip
    outs:
    - datasets/code2seq-java-large-test:
        cache: false
